- cmd/get.go
- cmd/profile.go
- cmd/rebuild.go
- cmd/repos_util.go
> Use non-bare repository

- cmd/get.go
- cmd/plugconf.go
- cmd/rm.go
- pathutil/pathutil.go
> plugConf -> plugconf

- cmd/disable.go
- cmd/enable.go
- cmd/list.go
- cmd/profile.go
> Support "-current" argument

- cmd/plugconf.go
* Fix: missing autocmd & :packadd of plugins which do not have plugconf
* Feature: s:load_on(): support multiple filetypes or excmds separated by ","
> Fix generating bundled plugconf

- cmd/plugconf.go
> Do not use VimEnter in bundled_plugconf.vim

- cmd/plugconf_util.go
- cmd/rm.go
> cmd/rm: Prohibit removing depended plugin

- cmd/get.go
> cmd/get: Don't overwrite existing plugconf

- README.md
- plugconf/plugconf.go
> s:load_on() -> s:loaded_on()

- Gopkg.lock
- Gopkg.toml
> dep ensure -update

- cmd/rebuild.go
> don't exit when user rc file exists (Fix #89)

- lockjson/lockjson.go
> Show error when lock.json version is newer than volt

- cmd/get.go
> 'volt get <repos>' show "no change" when repository exists

- README.md
- cmd/add.go
- cmd/get.go
- cmd/help.go
- cmd/migrate.go
- cmd/profile.go
- cmd/rebuild.go
- lockjson/lockjson.go
- lockjson/migration.go
- main.go
> Implement lock.json migration: v1 -> v2

- Makefile
- cmd/help.go
- cmd/self_upgrade.go
- cmd/version.go
- cmd/version_test.go
- httputil/httputil.go
- main.go
- plugconf/plugconf.go
> Add self-upgrade command

- cmd/add.go
- cmd/rebuild.go
- fileutil/fs.go
- logger/logger.go
Fix #94 
```
*$ time bin/volt rebuild -full
real    1m13.530s
user    0m0.531s
sys     0m13.594s
```
```
*$ time bin/volt rebuild -full
real    0m18.918s
user    0m2.453s
sys     0m13.641s
```
> Speed up full rebuild

- .travis.yml
- README.md
* Use ~Go 1.9.0~ -> Go 1.9.1
* Suppress some noisy email notifications
> Fix travis.yml

- cmd/build.go
- cmd/help.go
- cmd/profile.go
- pathutil/pathutil.go
> Add "volt profile rename" command

- cmd/get.go
- cmd/repos_util.go
```
$ cat ~/volt/repos/github.com/tyru/dummy/.git/config
[core]
bare = false
[remote "origin"]
url = https://github.com/tyru/dummy
fetch = +refs/heads/*:refs/remotes/origin/*
```
```
$ cat ~/volt/repos/github.com/tyru/dummy/.git/config
[core]
bare = false
[remote "origin"]
url = https://github.com/tyru/dummy
fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
remote = origin
merge = refs/heads/master
```
```diff
--- gitconfig.old.txt>2017-12-16 21:55:26.514775900 +0900
+++ gitconfig.new.txt>2017-12-16 21:55:30.042772800 +0900
@@ -3,3 +3,6 @@
[remote "origin"]
url = https://github.com/tyru/dummy
fetch = +refs/heads/*:refs/remotes/origin/*
+[branch "master"]
+        remote = origin
+        merge = refs/heads/master
```
https://github.com/src-d/go-git/issues/600#issuecomment-33085 …
> cmd/get: Set upstream branch

- cmd/get.go
- cmd/version.go
> Release v0.2.0

- cmd/self_upgrade.go
> [volt self-upgrade] Show release notes always

- cmd/version.go
> "volt help version" shows "Unknown command 'version'"

- CMDREF.md
- cmd/profile.go
`volt profile set -n {profile}` creates the profile unless it exists.
>  Implement '-n' flag of 'volt profile set'

- cmd/get.go
- config/config.go
> Add get.create_skeleton_plugconf option

- .travis.yml
- CMDREF.md
- Makefile
- README.md
- _scripts/update-readme.go
- cmd/build.go
- cmd/build_test.go
- cmd/builder/base.go
- cmd/builder/builder.go
- cmd/builder/copy.go
- cmd/builder/symlink.go
- cmd/buildinfo/buildinfo.go
- cmd/disable.go
- cmd/enable.go
- cmd/get.go
- cmd/get_test.go
- cmd/help.go
- cmd/list.go
- cmd/list_test.go
- cmd/profile.go
- cmd/profile_test.go
- cmd/rm.go
- cmd/rm_test.go
- cmd/version.go
- gitutil/gitutil.go
- internal/testutil/testutil.go
- lockjson/lockjson.go
- pathutil/pathutil.go
- pathutil/pathutil_test.go
- plugconf/plugconf.go
> Release v0.3.0

- LICENSE
- cmd/get.go
- plugconf/plugconf.go
> Improve excmd lazy load

- LICENSE
- cmd/get.go
- cmd/get_test.go
- cmd/version.go
- pathutil/pathutil.go
- pathutil/pathutil_test.go
- plugconf/plugconf.go
> Release v0.3.1

- plugconf/plugconf.go
> Fix warning message of s:config() function is found in plugconf files

- _shellcomp/volt
Fix #225
Add modified version of @AvianY's script.
> Bash completion

- _contrib/completion/bash
Various edge cases have been solved, such as completion for invalid subcommands etc.
> Fixed edge cases for bash completion

- Gopkg.lock
- Makefile
- vendor/github.com/xanzy/ssh-agent/pageant_windows.go
> Release v0.3.5a

- _contrib/completion/bash
- _contrib/completion/zsh
This PR adds the wrapper script for zsh completion.
> add zsh completion

- plugconf/plugconf.go
> End plugconf files with \n

- plugconf/plugconf.go
> Revert "End plugconf files with \n"

- lockjson/lockjson.go
- subcmd/get.go
> Sort entries in lockJSON (in lockjson.go)

- subcmd/migrate.go
> Fix: 'volt migrate' does not show help message

- pathutil/pathutil.go
- subcmd/build.go
- subcmd/get.go
- subcmd/migrate/lockjson.go
- subcmd/migrate/plugconf-config-func.go
- subcmd/profile.go
- subcmd/rm.go
- transaction/transaction.go
> Re-implement broken transaction by empty lock directory

- README.md
- plugconf/plugconf.go
* Fix `s/after/before/` in skeleton.
* Add `s:on_load_post()` to example config.
> Fix skeleton comment
