vim-volt/volt

cmd/add.go, cmd/disable.go, cmd/enable.go, cmd/help.go, cmd/list.go, cmd/plugconf.go, cmd/profile.go, cmd/query.go, cmd/rebuild.go, cmd/rm.go
```
cmd/add.go:27: Println arg list ends with redundant newline
```
=> Fix compile error: Println arg redundant newline

Gopkg.lock, cmd/add.go, cmd/get.go, cmd/help.go, cmd/plugconf.go, cmd/profile.go, cmd/rebuild.go, cmd/rm.go, pathutil/pathutil.go
Implement configuration per plugin (plugconf).
- if `s:load_on()` returns `start`, load plugin configuration by `autocmd VimEnter * call s:config_{number}()`
- if `s:load_on()` returns `filetype={pattern}`, load plugin configuration by `autocmd FileType {pattern} call s:config_{number}()`
- if `s:load_on()` returns `excmd={pattern}`, load plugin configuration by `autocmd CmdUndefined {pattern} call s:config_{number}()`
=> Support plugconf

transaction/transaction.go
=> Fix typo in transaction error text

README.md, cmd/get.go, cmd/help.go, cmd/plugconf.go, cmd/rm.go, pathutil/pathutil.go
* Unite user/system plugconf path
* path: $VOLTPATH/plugconf/<repos>.vim
* Remove '-a' option from 'volt plugconf list'
* Add '-p' option to 'volt rm' which removes also plugconf file
The plugconf path was changed:
* Before
* $VOLTPATH/plugconf/user/<repos>.vim
* $VOLTPATH/plugconf/system/<repos>.vim
* After
* $VOLTPATH/plugconf/<repos>.vim
Users can migrate existing plugconf files like:
```
$ mv ~/volt/plugconf/user/* ~/volt/plugconf/
$ rmdir ~/volt/plugconf/user
```
Currently no plugconf files are placed at https://github.com/vim-volt/plugconf-templates ,
so it's safe to ignore `~/volt/plugconf/system/*`.
=> Unite user/system plugconf path

cmd/rebuild.go
=> cmd/rebuild: updateNonBareGitRepos have to call Helptags (fix #76)

.travis.yml, Makefile, appveyor.yml, cmd/get_test.go, cmd/profile_test.go, cmd/rebuild.go, cmd/rm_test.go, internal/testutil/testutil.go, pathutil/pathutil.go
Fix #92 
* Introduce AppVeyor
* Fix test codes for windows
* Windows support
* Search vim executable: use `$VOLT_VIM` if defined, or find vim executable from PATH
=> Introduce AppVeyor CI (and fix failed tests on Windows)

lockjson/lockjson.go
When the target repository exists in multiple profiles in lock.json,
`ProfileList.RemoveAllReposPath()` method removes only the first entry...
So lockjson.Validate() (from lockjson.Write()) returns non-nil error.
```
$ bin/volt rm tyru/caw.vim
[ERROR] Failed to remove repository: 'github.com/tyru/caw.vim' (profiles[1].repos_path[1]) doesn't exist in repos
```
=> `volt rm <repos>` failed when it exists in multiple profiles

.travis.yml, fileutil/copyfile_generic.go, fileutil/copyfile_linux.go
Fix #128
* [Travis] Introduce macOS test
* Fix: `volt get <repos>` panicked on macOS
=> Fix: `volt get <repos>` panicked on macOS

cmd/self_upgrade.go
```
% volt self-upgrade
[INFO] Found update: v0.1.4-alpha -> v0.2.1
[ERROR] Failed to self-upgrade: fork/exec /home/thinca/.go/bin/volt: text file busy
```
P.S.
* Thanks @thinca for report on vim-jp slack.
* Thanks @mattn for suggesting the code.
=> "volt self-upgrade" fails to upgrade

logger/logger.go
ref. #153
* Use color.New().Fprintf() instead of fmt.Fprintf()
* Use mutex not to mix escape sequence wrongly
=> Fix broken output on Windows

cmd/get.go
[omnisharp-vim](https://github.com/OmniSharp/omnisharp-vim)のようなsubmoduleありのリポジトリでsubmoduleが取得・更新されるようにしました。
`submodule init`されていないワークツリーで、リモートに変更がなければそのままですが、`volt get -u`でワークツリーが更新されるタイミングで`git submodule update --init --recursive`のような動きになります。
初回の`volt get`でも同様にsubmoduleを取得します。
=> Update submodules on install or upgrade

.appveyor.yml
#201 was [failed](https://ci.appveyor.com/project/vim-volt/volt/build/391) because go1.9 commands are not always used.
Setting `GOROOT` should fix this.
=> [AppVeyor] Fix go version mismatch

plugconf/plugconf.go
Fix newline of bundled_plugconf.vim.
(`vimfiles/pack/volt/start/system/plugin/bundled_plugconf.vim`)
* before (eff2f161000b747ca3a2020989e2a4861846dd0e)
```
...
augroup END
let $MYVIMRC = 'C:\Users\xxx\volt\rc\default\vimrc.vim'let $MYGVIMRC = 'C:\Users\xxx\volt\rc\default\gvimrc.vim'
```
* after (409cd939f8413cd427c5cd9e40e99b03409854a8)
```
...
augroup END
let $MYVIMRC = 'C:\Users\xxx\volt\rc\default\vimrc.vim'
let $MYGVIMRC = 'C:\Users\xxx\volt\rc\default\gvimrc.vim'
```
--
=> Fix newline

subcmd/edit.go
- Fixes https://github.com/vim-volt/volt/issues/280
=> Remove erroneous call to `RemoveAllReposPath`

subcmd/get.go
- Closes https://github.com/vim-volt/volt/issues/255
=> Sort entries in lockJSON

lockjson/lockjson.go, pathutil/pathutil.go, subcmd/buildinfo/buildinfo.go, subcmd/get.go, subcmd/get_test.go, subcmd/profile.go, subcmd/rm.go, subcmd/rm_test.go
=> Avoid dup entries lock.json

.travis.yml, go.mod
On the latest go command appends `go 1.13` at the bottom of `go.mod`.
https://travis-ci.org/vim-volt/volt/jobs/537348218
```
$ go version
go version devel +d97bd5d07a Sat May 25 22:38:01 2019 +0000 linux/amd64
```
This PR avoids that.
=> [CI] Test only the nearest two major go versions

internal/testutil/testutil.go, subcmd/build_test.go, subcmd/get_test.go, subcmd/help_test.go, subcmd/list_test.go, subcmd/profile_test.go, subcmd/rm_test.go
Test directories that are created for testing are removed after
successful tests. Otherwise they clutter the tmp dir after executing
lots of tests.
There are still some volt-test-home* directories created that this PR doesn't catch.
=> Cleanup tmp dirs after test

README.md, go.sum, plugconf/plugconf.go
Provide function `s:should_load()` in plugconf with a default content of
"return 1" for unconditional loading.
This allows binding the loading of a plugin to certain conditions like
the availability of a certain vim function or patch level.
Closes: #256
=> Allow conditional plugin loading

go.mod
go.mod does not accept a patch version.
```
github.com/vim-volt/volt/go.mod:26: usage: go 1.23
```
=> Fix go.mod error

subcmd/builder/symlink.go
At the moment the actual error is ignored an a nil error is always
returned. This leads to the surprising result that only some arbitrary
repositories are symlinked on `volt build` if one update failed, but no
error is displayed to the user.
=> Return actual error when updating repos

plugconf/plugconf.go, plugconf/plugconf_test.go
close: #332 
- The `dependTo`/`dependedBy` fields were not slices of pointers, so the updated values were not reflected.
- The first value calculated was used as rank, so the result of rank calculation depended on the order before sorting.
=> Fix dep tree
